Feature book
andreykravchenkoo/BookLibraryProject pull request #1
Opened 2022-08-12 17:47 UTC by AndreyKravchenkoJava

2022-08-15 09:29 UTC, singeev commented
Сходу первый комментарий по коду: ты очень здорово разбил все на классы и методы! Т.е. налицо хорошее понимание ООП и концепции "класса". Плюс, уже видно разбиение приложения на "слои" - сервисы, репозитории... Очень круто!

2022-08-15 10:17 UTC, singeev requested changes

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/BookService.java
> +            bookRepository.bookList.add(new Book(nameAndAuthorArray[0], nameAndAuthorArray[1]));
Здесь ты используешь прямой доступ к `bookList` - переменной другого класса. Это нарушение инкапсуляции. Добавь к `BookRepository` новый метод `public void save(Book book)`.

И вызывай новый метод здесь:
```
if (matcher.find()) {
            bookRepository.save(new Book(nameAndAuthorArray[0], nameAndAuthorArray[1]));
}
```

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +    LibraryRepository libraryRepository = new LibraryRepository();
`private`

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        ReaderRepository readerRepository = new ReaderRepository();
вот эти две переменные, по хорошему тоже должны быть на уровне класса, а не метода.

В твоем коде это пока не очевидно, т.к. ты их используешь только внутри одного метода, но если вынести их на уровень класса - это будет соответствовать общепринятым правилам. И сделай их `private`.

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        System.out.println(readerRepository.readerList);
прямое обращение к внутренним полям класса - нарушение инкапсуляции. Используй методы `bookRepository.findAll()` - я о них писал выше.

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +
я не понял этот коммент, напиши подробнее, какую логику ты ожидаешь получить?

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +                    Reader reader = new Reader(readerRepository.readerList.get(j).getName());
Тут ты зря создаешь новые объекты для книги и читателя. Они у тебя уже есть в соответствующих репозиториях. Пользователь тебе ввел их `id`, тебе нужно просто взять готовые объекты из репозитория по их `id`. Примерно так `var bookToBorrow = bookRepository.findById(bookId)` и `var newBorrower = readerRepository.findById(readerId)`

Обрати внимание на использование `var` - там где тип переменной очевиден, не обязательно писать название класса.

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +            for (int j = 0; j < readerRepository.readerList.size(); j++) {
Ты усложнил код этими двумя циклами.

Правильнее будет получить просто обратиться к нужным репозиториям и запросить книгу по ее айди. То же самое с читателем.

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +                    libraryRepository.borrowedBooks.put(book, reader);
Снова прямой доступ к внутренним полям класса.

Используй метод, о котором я писал выше - `public void borrowBookToReader(Book book, Reader reader)`

2022-08-15 10:17 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +
Я разобрался. Проблема в том, что ты создаешь новые объекты при попытке "выдать" книгу. А нужно использовать уже имеющиеся. Я об этом написал в отдельном комментарии.

2022-08-17 15:23 UTC, AndreyKravchenkoJava commented on src/main/java/project/service/LibraryService.java
> +
Тут я не особо понял что ты имеешь ввиду, айдишники все равно съезжали, нашел решение в удалении двух классов сервисов, и добавления их логики в один общий LibraryService. Съезжали айдишники из-за дублирования во всех сервисах классов репозиториев

2022-08-17 15:26 UTC, AndreyKravchenkoJava commented on src/main/java/project/repository/BookRepository.java
> +        bookList.add(book3);
Когда я так делал, при добавлении нового объекта у меня вылазила ошибка. В интернете почитал, что List.of неизменяемый

2022-08-17 15:30 UTC, AndreyKravchenkoJava commented on src/main/java/project/service/LibraryService.java
> +
Скорее не из-за дублирования, а из-за создания новых классов репозиториев в других классах сервисах

2022-08-17 15:30 UTC, singeev commented on src/main/java/project/repository/BookRepository.java
> +        bookList.add(book3);
Да, ты прав. Я забыл про это.
Закрываю этот коммент.

2022-08-17 15:35 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +
Я не обратил внимания, если такое было.
При этом вижу, что ты исправил то, что я имел в виду. Результат достигнут - дублирования нет )
Закрываю коммент.

2022-08-17 15:47 UTC, singeev commented on src/main/java/project/repository/BookRepository.java
> +        return book;
Лишняя переменная, можно сразу делать `return`:
```
return bookList.stream()
    .filter(b -> b.getId() == bookId)
    .collect(Collectors.toList())
    .get(0);
```

2022-08-17 15:47 UTC, singeev commented on src/main/java/project/repository/ReaderRepository.java
> +        return reader;
Тоже сразу делай `return`

2022-08-17 15:47 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        System.out.println(libraryRepository.findAll().entrySet().stream().filter(r -> r.getValue().getId() == input).collect(Collectors.toList()));
Все корректно, но сложно читать. Было бы понятнее вот так:
```
libraryRepository.findAll().entrySet()
    .stream()
    .filter(r -> r.getValue().getId() == input)
    .forEach(System.out::println);
```

2022-08-17 15:47 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        System.out.println(libraryRepository.findAll().entrySet().stream().filter(b -> b.getKey().getId() == input).collect(Collectors.toList()));
Такое же пожелание.

2022-08-21 18:11 UTC, singeev commented on src/main/java/project/dao/LibraryDAOImpl.java
> +    }
Удали методы, которые не нужны

2022-08-21 18:11 UTC, singeev commented on src/main/java/project/dao/LibraryDAOImpl.java
> +                "ORDER BY reader.id";
Ты джойнишь 3 таблицы, но используешь колонки только одной из них. Упрости запрос, не нужна таблица `reader`

2022-08-21 18:11 UTC, singeev commented on src/main/java/project/dao/LibraryDAOImpl.java
> +                "ORDER BY reader.id";
Тут то же самое - лишняя таблица.

2022-08-21 18:11 UTC, singeev commented on src/main/java/project/dao/LibraryDAOImpl.java
> +        // Понимаю что не сделал его правильно, но почему-то для каждого читателя выводится его последняя заимствованная книга.
Посмотри вот эту статью: https://stackoverflow.com/questions/16461735/jdbc-template-one-to-many
Там похожий пример, тебе его можно взять, как отправную точку.

2022-08-21 18:15 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/BookDAOImpl.java
> +    public Book update(Book object) {
Назвал так из-за имплементации интерфейса, я наверное его уберу, пусть будет просто три отдельных класса dao

2022-08-21 18:17 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAOImpl.java
> +public class LibraryDAOImpl {
Ты прав, чуть-чуть забылся и назвал так) Исправлю

2022-08-21 18:18 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAOImpl.java
> +    }
Их я сделал наперед, думал потом сделаю, чтобы были CRUD функции

2022-08-22 11:55 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAOImpl.java
> +                "ORDER BY reader.id";
Вчера не ответил из-за того, что не понял тебя) Исправил

2022-08-22 12:25 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/BookDAOImpl.java
> +                return Optional.ofNullable(book);
Ты говорил, что возвращать null такое себе, поэтому нужно возвращать Optional. Но метод в котором я использую `getBook()` возвращает Optional

2022-08-22 13:49 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAOImpl.java
> +                "ORDER BY reader.id";
И тут исправил

2022-08-22 14:07 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAOImpl.java
> +        // Понимаю что не сделал его правильно, но почему-то для каждого читателя выводится его последняя заимствованная книга.
Как я понял, мне нужно делать проверку на то, есть ли следующий читатель в Мапе. Если его нет, читаю дальше текущие книги. Правильно?)

2022-08-22 14:36 UTC, singeev commented on src/main/java/project/dao/BookDAOImpl.java
> +                return Optional.ofNullable(book);
Я тебя запутал ))
Да, нужно возвращать тип `Optional<Book>`, но если в БД книги нет - нужно чтобы этот опшнл был пустой. А у тебя он никогда не будет пустой, даже если такой книги нет - ты кладешь внутрь `optional` объект книги. Это не правильно.

2022-08-22 14:37 UTC, singeev commented on src/main/java/project/dao/LibraryDAOImpl.java
> +    }
Не факт, что они вообще тебе когда-нибудь понадобятся.
Один из принципов чистого кода - YAGNI. Почитай про него и бери на вооружение!

2022-08-22 14:39 UTC, singeev commented on src/main/java/project/dao/LibraryDAOImpl.java
> +        // Понимаю что не сделал его правильно, но почему-то для каждого читателя выводится его последняя заимствованная книга.
Да, правильно.
У тебя в resultSet будет один и тот же читатель повторяться столько раз - сколько у него есть книг.
Тебе нужно создать цикл и внутри него идти по строкам. Появился новый читатель - создаешь его. Новая книга - создаешь ее. Читатель старый? - значит это просто вторая книга для него. Читатель новый? - создаешь его и затем книги для него.
Как-то так.

2022-08-26 17:35 UTC, singeev commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
Поменяй на java 17, как мы договорились в группе.
Если у тебя еще нет JDK 17 в системе - установи. 
16 можно убрать, он тебе больше не понадобится.

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/console/ConsoleUI.java
> +    private void getCover() {
Название метода `getCover()` - не отражает его сути. По факту этот метод не только показывает меню, но фактически внутри него и происходит вся работа.
Придумай более подходящее название. Например `runLibrary` или `talkToUser'...

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/console/ConsoleUI.java
> +        getMessage();
А вот этот метод - как раз get cover. Но я бы предложил что-то ближе к истине, например `showMainMenu()`

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/console/ConsoleUI.java
> +        String choice = getChoice();
Тут у тебя лишний код, внутри метода `getChoice()`. В целом - это очень правильный подход - выносить куски кода в отдельные методы. Но там внутри ты просто берешь данные из консоли и конвертируешь в строку.
А можно это делать сразу, за одно действие. И тогда это уже не стоит выносить в отдельный метод.
Вот так это может выглядеть:
```suggestion
        var choice = scanner.nextLine();
```

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/console/ConsoleUI.java
> +    }
и тогда этот метод можно удалить

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/console/ConsoleUI.java
> +        System.out.println("Type 'exit' to stop program and exit!");
Замени это на multi-line String. В новых версиях джава нужно этим пользоваться.

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/dao/BookDAO.java
> +             PreparedStatement preparedStatement = connection.prepareStatement(SQL_SAVE_BOOK)) {
Не вижу нигде чтобы ты использовал ключевое слово `var`. Ты же не на java 4 пишешь )
Почитай, что это такое и когда его лучше использовать.
Например, тут, спокойно можно это делать.
```
var connection = ...
var preparedStatement = ...
```

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/dao/LibraryDAO.java
> +    public boolean save(int bookID, int readerId) {
Название метода не соответствует его назначению. Придумай что-то более понятное.
Например `borrowBookIdToReaderId(int bookId, int readerId)`

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/dao/LibraryDAO.java
> +    public boolean delete(int bookId, int readerId) {
Снова название. Запомни на будущее - это одно из условий хорошо читаемого кода, когда у методов названия сходу подсказывают, что именно происходит внутри.
Например `returnBookIdFromReaderId(int bookId, int readerId)`

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/dao/LibraryDAO.java
> +    public List<Book> getReaderBorrowedBook(int readerId) {
`findAllBorrowedBooksByReaderId(int readerId)` - длинные названия методов это норм.

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/dao/LibraryDAO.java
> +    public List<Reader> getReadersByCurrentBook(int bookId) {
`findAllReadersByBookId(int bookId)`

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/dao/LibraryDAO.java
> +    private Reader getBorrowedReader(ResultSet resultSet) {
Обычно такие методы (мапперы) называют как-то короче, например `mapToReader(ResultSet resultSet)` или `toReader(ResultSet resultSet)`

2022-08-26 17:35 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        System.out.println(bookDAO.findAll());
Предлагаю тебе весь этот класс перечитать и переделать на лямбды и новый синтаксис, где это возможно.
Например тут лучше будет
```suggestion
        bookDAO.findAll().forEach(System.out::println);
```

2022-08-27 11:49 UTC, AndreyKravchenkoJava commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
Сделано

2022-08-27 11:52 UTC, AndreyKravchenkoJava commented on src/main/java/project/console/ConsoleUI.java
> +    private void getCover() {
Исправил

2022-08-27 11:52 UTC, AndreyKravchenkoJava commented on src/main/java/project/console/ConsoleUI.java
> +        getMessage();
Исправил

2022-08-27 11:54 UTC, AndreyKravchenkoJava commented on src/main/java/project/console/ConsoleUI.java
> +        String choice = getChoice();
Да, так лучше, исправил

2022-08-27 12:01 UTC, AndreyKravchenkoJava commented on src/main/java/project/console/ConsoleUI.java
> +        System.out.println("Type 'exit' to stop program and exit!");
Сделано

2022-08-28 12:19 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/BookDAO.java
> +             PreparedStatement preparedStatement = connection.prepareStatement(SQL_SAVE_BOOK)) {
Я прочитал про var. Не использовал по причине того, что мне почему-то наоборот удобней объявлять переменные как раньше. Сейчас в проектах всегда используют его?

2022-08-28 12:20 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAO.java
> +    public boolean save(int bookID, int readerId) {
Испарвил

2022-08-28 12:20 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAO.java
> +    public boolean delete(int bookId, int readerId) {
Исправил

2022-08-28 12:21 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAO.java
> +    public List<Book> getReaderBorrowedBook(int readerId) {
Исправил

2022-08-28 12:22 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAO.java
> +    public List<Reader> getReadersByCurrentBook(int bookId) {
Испарвил

2022-08-28 12:25 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/LibraryDAO.java
> +    private Reader getBorrowedReader(ResultSet resultSet) {
Исправил

2022-08-28 12:27 UTC, AndreyKravchenkoJava commented on src/main/java/project/service/LibraryService.java
> +        System.out.println(bookDAO.findAll());
Исправил, но пока без использования var

2022-08-29 15:29 UTC, singeev commented on pom.xml
> +        <maven.compiler.target>16</maven.compiler.target>
Если и сделано, то в репо этого не видно.

2022-08-29 15:30 UTC, singeev commented on src/main/java/project/connector/ConnectionCreator.java
> +            connection = DriverManager.getConnection(URL, USER_NAME, PASSWORD);
можно сразу делать `return DriverManager.getConnection(URL, USER_NAME, PASSWORD);`

2022-08-29 17:50 UTC, AndreyKravchenkoJava commented on src/main/java/project/connector/ConnectionCreator.java
> +            Class.forName(JDBC_DRIVER);
Да, читал об этом, но когда делал задания из книги по JDBC почему-то не работало. Исправил

2022-08-29 17:50 UTC, AndreyKravchenkoJava commented on src/main/java/project/connector/ConnectionCreator.java
> +            connection = DriverManager.getConnection(URL, USER_NAME, PASSWORD);
Исправил

2022-09-02 08:49 UTC, singeev commented on src/main/java/project/console/ConsoleUI.java
> +        System.out.println("Type 'exit' to stop program and exit!");
Ну почти ))
Погляди вот тут: https://www.baeldung.com/java-multiline-string

Вообще, как-нибудь выбери время, залезь в гугл и почитай, что нового добавляли в язык java начиная с версии 8 (т.е. почитай про разницу между 7 и 8) и заканчивая версиями 17-18.
Нужно понимать, какие новые фичи есть в языке, какая версия джава выглядит наиболее привлекательно, а какая - особо и не интересна.

2022-09-02 08:52 UTC, singeev commented on src/main/java/project/dao/BookDAO.java
> +             PreparedStatement preparedStatement = connection.prepareStatement(SQL_SAVE_BOOK)) {
Тот факт, что тебе так удобнее, не спасет тебя от того, что в новых проектах будет куча этих `var`.
Если тебе они не нравятся - не пиши. Но есть вероятность, что ты придешь работать на проект, где использвание `var` будет обязательно в каких-то случая и тебе не будут апрувить пул риквесты, если ты не будешь их использовать.
Предлагаю, в качестве тренировки все же иногда их использовать, чтобы просто получить практический опыт и иметь свое мнение о том, когда это удобно, а когда нет.

2022-09-02 08:55 UTC, singeev commented on src/main/java/project/dao/LibraryDAO.java
> +    private Book mapToBorrowedBook(ResultSet resultSet) {
название метода вводит в заблуждение - в твоем проекте нет класса `BorrowedBook`, значит не может быть и такого маппинга. Переименуй в `mapToBook(ResultSet resultSet)`

2022-09-02 08:57 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        bookList.forEach(System.out::println);
Т.к. у тебя тут единственное использование переменной, обычно ее не создают и пишут код в одно выражение:
```
libraryDAO.findAllBorrowedBooksByReaderId(input)
  .forEeach(System.out::println);
```

2022-09-02 08:58 UTC, singeev commented on src/main/java/project/service/LibraryService.java
> +        readerList.forEach(System.out::println);
Такая же ситуация - лишняя переменная.

2022-09-02 09:02 UTC, AndreyKravchenkoJava commented on src/main/java/project/console/ConsoleUI.java
> +        System.out.println("Type 'exit' to stop program and exit!");
Хорошо, прочитаю на досуге)

2022-09-02 09:02 UTC, AndreyKravchenkoJava commented on src/main/java/project/dao/BookDAO.java
> +             PreparedStatement preparedStatement = connection.prepareStatement(SQL_SAVE_BOOK)) {
Понял, тогда буду начинать использовать

2022-09-02 11:27 UTC, AndreyKravchenkoJava commented
Исправил

2022-09-02 11:50 UTC, AndreyKravchenkoJava commented on src/main/java/project/service/LibraryService.java
> +        readerList.forEach(System.out::println);
Сделал

2022-09-04 13:44 UTC, merged